spring.application.name=BloodDonationManagementSystem
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/blooddb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Venkey@2005}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

server.port=${PORT:8080}

# Spring Mail (Brevo SMTP) Config
# To enable real emails, specify your Brevo SMTP username (login email) and your Brevo SMTP Key.
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=venkateshkurella369@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


